    Task 2 Chi Squared Test.
![equation](https://wikimedia.org/api/rest_v1/media/math/render/svg/69331c954dbe94da0301bf56d14e4394ef545b08)
To do a Chi Squared Test:
<br/>
Step1: State the null hypothesis(Ho) and the alternative(H1)
<br/>
Defining the null hypothesis (H0) which states that there is no relation between the variables. An alternate hypothesis would state that there is a significant relation between the two.
****
<br/>
Step2: Choose leve of significance(alpa)
****
<br/>
Step3. Find critical values
****
<br/>
Step4. Find test statistic
****
<br/>
Step5 Draw your conclusions




https://www.geeksforgeeks.org/python-pearsons-chi-square-test/

#### The aim of the test is to conclude whether the two variables( collar type and choice of A,B,C,D ) are related to each other.

#### Using p-value:
We define a significance factor to determine whether the relation between the variables is of considerable significance. 
Generally a significance factor or alpha value of 0.05 is chosen. 
This alpha value denotes the probability of erroneously rejecting H0 when it is true. 
A lower alpha value is chosen in cases where we expect more precision. 
If the p-value for the test comes out to be strictly greater than the alpha value, then H0 holds true.

#### Using chi-square value:
If our calculated value of chi-square is less or equal to the tabular(also called critical) value of chi-square, then H0 holds true.

#### Expected Values Table :

Next, we prepare a similar table of calculated(or expected) values. 
To do this we need to calculate each item in the new table as : 

![chisquared](https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-f20e7e94d2c66cf8c42e73207ecb16b2_l3.svg)

Create the chi-squared table

From the chi-squared table, we obtain the total of the last column, which gives us the calculated value of chi-square. <br/> 

Now, we need to find the critical value of chi-square. We can obtain this from a table. 
To use this table, we need to know the degrees of freedom for the dataset.  
The degrees of freedom is defined as : (no. of rows – 1) * (no. of columns – 1).



Now, let us look at the table and find the value corresponding to 2 degrees of freedom and 0.05 significance factor :

![critial table](https://media.geeksforgeeks.org/wp-content/uploads/20200604234722/download.png)

The tabular or critical value of chi-square here is  5.991
Hence,

![](https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-4c1a1448d2d26bd341a57defecfd3aa9_l3.svg)

Therefore, H0 is accepted, that is, the variables do not have a significant relation.
Next, let us see how to perform the test in Python.

Null hypothesis:<br/>
We start by defining the null hypothesis (H0) which states that <br/>there is no relation between the variables. 
An alternate hypothesis would state that there is a significant relation between the two

In [45]:
from scipy.stats import chi2_contingency
# defining the table 

data = [[90, 60, 104,95], [30, 50, 51,20],[30,40,45,35]] 
stat, p, dof, expected = chi2_contingency(data)
print("stat is ",stat)
print("Expected Values Table\n" , expected)
print("Degrees of Freedom ",dof)
# interpret p-value 
alpha = 0.05
print("alpha = ",alpha)
print("This alpha value denotes the probability of erroneously rejecting H0 when it is true")
print("If the p-value for the test comes out to be strictly greater than the alpha value, then H0 holds true.")
print("p value is " + str(p)) 
if p <= alpha: 
    print('Dependent (reject H0)') 
else: 
    print('Independent (H0 holds true)') 

stat is  24.5712028585826
Expected Values Table
 [[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
Degrees of Freedom  6
alpha =  0.05
This alpha value denotes the probability of erroneously rejecting H0 when it is true
If the p-value for the test comes out to be strictly greater than the alpha value, then H0 holds true.
p value is 0.0004098425861096696
Dependent (reject H0)


Therefore, H0 is rejected, that is, the variables do have a significant relation.

In [14]:
# Manually calculating the chi squared. Not diffcult on paper.
# Having a go in pyhton
# import libraries
import numpy as np 
import pandas as pd
import scipy
from scipy.stats import chi2
# create contingency table with floats to avoid datatype issues with pd.DataFrame.at 
ar=np.array([[90, 60, 104,95], [30, 50, 51,20],[30,40,45,35]])    
df=pd.DataFrame(ar, columns=["A", "B","C","D"])
df.index=["White collar", "Blue collar", "No collar"] 
df2=df.copy() # create contingency table with the marginal totals and the grand total. 
df2.loc['Total']= df2.sum(numeric_only=True, axis=0)
df2.loc[:,'Total'] = df2.sum(numeric_only=True, axis=1)
df2

A    B    C    D  Total
White collar   90   60  104   95    349
Blue collar    30   50   51   20    151
No collar      30   40   45   35    150
Total         150  150  200  150    650

Expected Values Table 

![](https://www.geeksforgeeks.org/wp-content/ql-cache/quicklatex.com-ddfefcd8d9895016ae4991b191e07bfd_l3.svg)

In [41]:
row_total = df2.iloc[0]["Total"]
column_total=df2.loc["Total"][0]
grand_total = df2.loc["Total"][4]
ans= (row_total*column_total)/grand_total
ans

80.53846153846153

Loop over this cal, for loop.